from enum import Enum as pyEnum


class ConversationStepsEnum(pyEnum):
    CHOOSE_SUBCATEGORY_REPAIR = 1
    CHOOSE_SUBCATEGORY_BUY_SELL = 2
    CHOOSE_SUBCATEGORY_CREDIT_LEASING = 3
    CHOOSE_SUBCATEGORY_INSURANCE = 4
    CHOOSE_SUBCATEGORY_OTHER_QUESTION = 5

    CHOOSE_CAR_REGISTRATION_NUMBER = 6
    CHOOSE_CAR_MILEAGE = 7
    ADD_REPAIR_DESCRIPTION = 8

    ADD_CLIENT_PHONE_NUMBER = 9
